### ISSUE TITLE
Is vectorx/aggx maintained?

### ISSUE THREAD

**Issue by cambiata** [gameduell/vectorx#25]
@track3r @nensanders @clue4gd
Hi Gameduell developers!

I just want to ask about the status of the vectorx/aggx libraries.
Are they still maintained?
Any future plans for these libraries?

Best! / Jonas

**Comment by dejan-gd** [comment]
Hi @cambiata,

I'm sorry, we do not maintain our Haxe libraries anymore. Also we do not have any plans to change that.

Best,
Dejan

**Comment by cambiata** [comment]
Thanks for answer!

Would it be ok if I ask around if anyone would like to fork and continue the development?

**Comment by nensanders** [comment]
Hi Jonas,

now that you brought the topic up, I thought about porting it to C# to use with Unity, because it is indeed pretty powerful. (Maybe a good Junior/Regular learning task) Unfortunately, I don't have time for that and there are probably already vector solutions for Unity.

Nice hearing from you. 
Feel free to ask me any question about the implementation details.

Best
Sven

**Comment by cambiata** [comment]
I've setup a test project just to get going with the aggx library. https://github.com/cambiata/aggx-tryout

No use of Duell tools, no OpenGl - just simple output from the FontEngine this far. Maybe there can be some traction on this - aggx has the only more develped font rendering engine for Haxe that I'm aware of. And you guys have invested soo much work into this project - it would be a pity if it didn't survive in any form.

A will credit you, GameDuell and Maxim at the best of my ability. If you have opinions, objections or ideas, please bring'em on!

**Comment by dejan-gd** [comment]
Hi @cambiata, many thanks for crediting us. Good luck with the project!
Best,
Dejan

**Comment by catdawg** [comment]
Hi @cambiata!

one objective of making this opensource was so that it actually would survive in some form :) Thanks a lot for this and good luck with the project!

Cheers,
Rui

**Comment by nensanders** [comment]
Hi @cambiata,
2 days ago, I managed to get vectorx and aggx examples running and drawing fonts and vectors using Haxe 3.2.1 Python 3.5 and the duelltool version you get with haxelib install duell (on a mac).
For vectorx make sure you are NOT depending on the library svgcompiler (in the duell library xml)
Newer versions don't work because some dependencies were not updated/maintained.

My plan is to port it to Jai once the language is out. https://www.twitch.tv/videos/342048921

For font rendering aggx is ok; but for proper lay-outing (multi-line, alignment, etc) you probably want vectorx. Though, I don't recall if the open source version is up to date. Seems quite buggy on HTML5. I didn't try iOS/Android.

Greetings from Hamburg,
Sven
